version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./images/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - default
    depends_on:
      - php
      - adminer

  php:
    build: images/php
    volumes:
      - ./images/php/php.ini:/usr/local/etc/php.ini
      - ./src:/var/www/html
    networks:
      - default

  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}